// Suggestions de catégories GBP (libellés français) pour les champs
// catégorie du wizard et de la création de projet — un datalist natif :
// on suggère, la saisie reste LIBRE. Ce n'est PAS le référentiel officiel
// de Google (categories.list exige l'accès API, en attente) : liste
// curatée des catégories courantes pour la clientèle de Küa (métiers de
// la construction et services locaux QC). À remplacer par un picker
// branché sur categories.list à l'approbation de l'API.

export const GBP_CATEGORY_SUGGESTIONS: string[] = [
  // Construction & rénovation
  "Entrepreneur général",
  "Couvreur",
  "Électricien",
  "Plombier",
  "Entrepreneur en excavation",
  "Entrepreneur en maçonnerie",
  "Entrepreneur en béton",
  "Entrepreneur en pavage",
  "Entrepreneur en isolation",
  "Entrepreneur en revêtement extérieur",
  "Entrepreneur en cloisons sèches",
  "Entrepreneur en démolition",
  "Entrepreneur en clôtures",
  "Entrepreneur en revêtements de sol",
  "Entrepreneur en piscines",
  "Entrepreneur en chauffage",
  "Entrepreneur en climatisation",
  "Menuisier",
  "Ébéniste",
  "Peintre en bâtiment",
  "Plâtrier",
  "Carreleur",
  "Vitrier",
  "Soudeur",
  "Serrurier",
  "Ramoneur",
  "Inspecteur en bâtiment",
  "Arpenteur-géomètre",
  "Architecte",
  "Service d'installation de gouttières",
  "Service d'installation de fenêtres",
  "Fournisseur de portes de garage",
  // Extérieur & entretien
  "Paysagiste",
  "Architecte paysagiste",
  "Service de déneigement",
  "Service d'entretien de pelouse",
  "Service d'entretien d'arbres",
  "Service de nettoyage résidentiel",
  "Service de nettoyage commercial",
  "Service de nettoyage de vitres",
  "Service de lutte antiparasitaire",
  "Service de restauration après dégât d'eau",
  "Entreprise de déménagement",
  "Service de remorquage",
  // Santé & soins
  "Clinique dentaire",
  "Dentiste",
  "Clinique médicale",
  "Pharmacie",
  "Optométriste",
  "Physiothérapeute",
  "Chiropraticien",
  "Massothérapeute",
  "Vétérinaire",
  // Services professionnels
  "Comptable",
  "Cabinet d'avocats",
  "Notaire",
  "Courtier d'assurances",
  "Agence immobilière",
  "Agent immobilier",
  "Agence de marketing",
  "Photographe",
  // Commerces & restauration
  "Restaurant",
  "Pizzéria",
  "Café",
  "Boulangerie",
  "Pâtisserie",
  "Traiteur",
  "Fleuriste",
  "Salon de coiffure",
  "Salon de barbier",
  "Salon de beauté",
  "Atelier de réparation automobile",
  "Concessionnaire automobile",
  "Garderie",
  "École de conduite",
  "Gym",
  "Hôtel",
];
